"""Crypto parity against authoritative TypeScript vectors.

Vectors are generated by ``nango-py/tools/crypto_vectors.gen.mjs``, which
replicates the TS algorithms from ``node:crypto`` so Python proves byte-for-byte
compatibility with ``packages/keystore/lib/utils/encryption.ts`` and
``packages/utils/lib/encryption.ts``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from cryptography.exceptions import InvalidTag

from nango_py.shared.crypto import (
    decrypt_aes_gcm,
    decrypt_api_secret,
    encrypt_aes_gcm,
    hash_secret,
)

VECTORS_PATH = (
    Path(__file__).resolve().parents[2]
    / "contract"
    / "fixtures"
    / "crypto"
    / "parity_vectors.json"
)
VECTORS = json.loads(VECTORS_PATH.read_text())


def test_pbkdf2_matches_ts_vectors() -> None:
    for vector in VECTORS["pbkdf2"]:
        assert hash_secret(vector["plaintext"], vector["encryption_key"]) == vector["hash"]


def test_pbkdf2_known_ts_fixture() -> None:
    assert (
        hash_secret("nango_connect_session_abcdef", "test-encryption-key")
        == "MboriZDg73s23cGPxPk+rOLeyMzd3kq1qSjrOLJVQtQ="
    )


def test_aes_gcm_decrypt_recovers_ts_plaintext() -> None:
    for vector in VECTORS["aes_gcm"]:
        assert (
            decrypt_aes_gcm(
                vector["ciphertext"],
                vector["iv"],
                vector["tag"],
                vector["key_base64"],
            )
            == vector["plaintext"]
        )


def test_aes_gcm_round_trip() -> None:
    key = VECTORS["aes_gcm"][0]["key_base64"]
    ciphertext, iv, tag = encrypt_aes_gcm("round-trip-secret", key)
    assert decrypt_aes_gcm(ciphertext, iv, tag, key) == "round-trip-secret"


def test_decrypt_api_secret_passthrough_when_unencrypted() -> None:
    assert decrypt_api_secret("plain-secret", None, None, "key") == "plain-secret"
    assert decrypt_api_secret("plain-secret", "", "", "") == "plain-secret"


def test_decrypt_api_secret_decrypts_when_encrypted() -> None:
    vector = VECTORS["aes_gcm"][0]
    assert (
        decrypt_api_secret(
            vector["ciphertext"],
            vector["iv"],
            vector["tag"],
            vector["key_base64"],
        )
        == vector["plaintext"]
    )


def test_aes_gcm_tampered_tag_raises() -> None:
    vector = VECTORS["aes_gcm"][0]
    tampered_tag = "AAAA" + vector["tag"][4:]
    with pytest.raises(InvalidTag):
        decrypt_aes_gcm(vector["ciphertext"], vector["iv"], tampered_tag, vector["key_base64"])


def test_hash_secret_passthrough_when_no_key() -> None:
    assert hash_secret("plain-secret", "") == "plain-secret"